### ISSUE TITLE
Environment variable BOTFUEL_APP_TOKEN is not defined.

### ISSUE THREAD

**Issue by villa9393** [Botfuel/botfuel-sample-starter#10]
Hi I got the following error msg

warn: [Environment] Environment variable BOTFUEL_APP_TOKEN is not defined.
2018-08-21T07:57:38.659Z - error: [Run] BOTFUEL_APP_ID and BOTFUEL_APP_KEY are required to use Botfuel NLU. Error: BOTFUEL_APP_ID and BOTFUEL_APP_KEY are required to use Botfuel NLU.
    at checkCredentials (c:\Users\10209288\Desktop\botfuel-sample-starter-master\node_modules\botfuel-dialog\build\utils\environment.js:54:13)
    at new Bot (c:\Users\10209288\Desktop\botfuel-sample-starter-master\node_modules\botfuel-dialog\build\bot.js:68:5)
    at _callee$ (c:\Users\10209288\Desktop\botfuel-sample-starter-master\node_modules\botfuel-dialog\build\run.js:53:18)
    at tryCatch (c:\Users\10209288\Desktop\botfuel-sample-starter-master\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (c:\Users\10209288\Desktop\botfuel-sample-starter-master\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (c:\Users\10209288\Desktop\botfuel-sample-starter-master\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (c:\Users\10209288\Desktop\botfuel-sample-starter-master\node_modules\botfuel-dialog\build\run.js:4:191)
    at c:\Users\10209288\Desktop\botfuel-sample-starter-master\node_modules\botfuel-dialog\build\run.js:4:437
    at new Promise (<anonymous>)
    at c:\Users\10209288\Desktop\botfuel-sample-starter-master\node_modules\botfuel-dialog\build\run.js:4:99

**Comment by KevinDepuydt** [comment]
Hello @villa9393 

To use this sample bot please follow [this step](https://github.com/Botfuel/botfuel-sample-starter#create-an-app) of the README to create an app on Botfuel Trainer (it's free).

When your app is ready to use, go to the **App settings** menu where you can copy your credentials.

After that you can follow [this step](https://github.com/Botfuel/botfuel-sample-starter#how-to-run-the-bot) of the README to clone and start your bot.

If you need help, see our [Getting Started](https://tutorials.botfuel.io/#/codelab/getting-started?step=1) to learn how to run a bot in minutes or the [Concepts](https://docs.botfuel.io/platform/concepts/) for explanations about the internals of the SDK.

**Comment by VaishnaviKillekar** [comment]
'BOTFUEL_APP_TOKEN' is not recognized as an internal or external command,
operable program or batch file.

I get this every time I run the npm start command along with the credentials.

**Comment by sreshtatwinkle** [comment]
'BOTFUEL_APP_TOKEN' is not recognized as an internal or external command,
operable program or batch file.

I get this every time I run the npm start command along with the credentials. 
can u please help me !
